# -*- coding: utf-8 -*-
"""UASBengkod

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m08VMDr_kJamgDC8c2nA6otvVm0Ahz6m
"""

from google.colab import drive
drive.mount('/content/drive')

# Import library yang diperlukan
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import joblib
import time
import missingno as msno
import warnings
warnings.filterwarnings('ignore')

# Set style untuk visualisasi
plt.style.use('seaborn-v0_8')
sns.set_palette("viridis")
plt.rcParams['figure.figsize'] = (10, 6)

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# ===========================================================
# 1. EDA (EXPLORATORY DATA ANALYSIS)
# ===========================================================
print("="*50)
print("1. EKSPLORASI AWAL")
print("="*50)

# Tampilkan 5 baris pertama
print("\n5 Baris Pertama Dataset:")
print(df.head())

# Tampilkan ringkasan dataset (info)
print("\nInformasi Dataset:")
print(df.info())

# Tampilkan statistik deskriptif
print("\nStatistik Deskriptif:")
print(df.describe(include='all'))

# 2. IDENTIFIKASI MISSING VALUE
print("\n" + "="*50)
print("2. IDENTIFIKASI MISSING VALUE")
print("="*50)

# Hitung persentase missing value untuk setiap kolom
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100

# Buat DataFrame untuk menampilkan hasil
missing_df = pd.DataFrame({
    'Jumlah Missing': missing_values,
    'Persentase (%)': missing_percentage
}).sort_values('Persentase (%)', ascending=False)

print("\nPersentase Missing Value per Kolom:")
print(missing_df[missing_df['Persentase (%)'] > 0])

# Visualisasi missing value dengan diagram batang
plt.figure(figsize=(12, 6))
sns.barplot(x=missing_percentage.index, y=missing_percentage.values)
plt.title('Persentase Missing Value per Kolom', fontsize=16)
plt.xlabel('Kolom', fontsize=12)
plt.ylabel('Persentase (%)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.ylim(0, max(missing_percentage.values) + 1)
plt.tight_layout()
plt.savefig('missing_value_percentage.png')
plt.show()

# Tampilkan visualisasi matrix missing value
plt.figure(figsize=(15, 8))
msno.matrix(df, fontsize=12)
plt.title('Missing Value Matrix', fontsize=16)
plt.tight_layout()
plt.savefig('missing_value_matrix.png')
plt.show()

# 3. VISUALISASI DISTRIBUSI TARGET (CHURN)
print("\n" + "="*50)
print("3. VISUALISASI DISTRIBUSI TARGET (CHURN)")
print("="*50)

# Hitung distribusi nilai pada kolom Churn
churn_counts = df['Churn'].value_counts()
churn_percentage = (churn_counts / len(df)) * 100

print("\nDistribusi Pelanggan Berdasarkan Status Churn:")
print(f"Total pelanggan: {len(df)}")
print(f"Pelanggan yang tetap (No): {churn_counts['No']} ({churn_percentage['No']:.2f}%)")
print(f"Pelanggan yang churn (Yes): {churn_counts['Yes']} ({churn_percentage['Yes']:.2f}%)")

# Buat visualisasi distribusi target
plt.figure(figsize=(10, 6))
ax = sns.countplot(x='Churn', data=df, palette='viridis')
plt.title('Distribusi Pelanggan Berdasarkan Status Churn', fontsize=16)
plt.xlabel('Status Churn', fontsize=12)
plt.ylabel('Jumlah Pelanggan', fontsize=12)

# Tambahkan label persentase pada bar chart
total = len(df)
for p in ax.patches:
    percentage = f'{100 * p.get_height() / total:.1f}%'
    x = p.get_x() + p.get_width() / 2
    y = p.get_height()
    ax.annotate(f'{percentage}\n({int(p.get_height())})', (x, y),
                ha='center', va='center', xytext=(0, 10),
                textcoords='offset points', fontsize=12)

plt.tight_layout()
plt.savefig('churn_distribution.png')
plt.show()

# 4. ANALISIS KORELASI
print("\n" + "="*50)
print("4. ANALISIS KORELASI")
print("="*50)

# Konversi TotalCharges ke numerik (ada beberapa nilai yang tidak bisa dikonversi)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Isi nilai yang hilang pada TotalCharges dengan median
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

# Identifikasi fitur numerik
numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
print(f"\nFitur numerik yang dianalisis: {numerical_features}")

# Konversi target Churn ke numerik untuk analisis korelasi
df_churn_num = df.copy()
df_churn_num['Churn'] = df_churn_num['Churn'].map({'Yes': 1, 'No': 0})

# Hitung korelasi antara fitur numerik dan target
correlation = df_churn_num[numerical_features + ['Churn']].corr()

print("\nMatriks Korelasi:")
print(correlation)

# Buat heatmap korelasi
plt.figure(figsize=(12, 10))
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.5,
            annot_kws={'size': 12}, cbar_kws={'label': 'Koefisien Korelasi'})
plt.title('Heatmap Korelasi Fitur Numerik dengan Target Churn', fontsize=16)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig('correlation_heatmap.png')
plt.show()

# Analisis korelasi dengan target Churn
churn_corr = correlation['Churn'].sort_values(ascending=False)
print("\nKorelasi Fitur Numerik dengan Target Churn:")
print(churn_corr)

# Visualisasi scatter plot antara tenure dan MonthlyCharges dengan warna berdasarkan Churn
plt.figure(figsize=(12, 8))
sns.scatterplot(x='tenure', y='MonthlyCharges', hue='Churn', data=df,
                palette='viridis', alpha=0.7, s=100)
plt.title('Hubungan antara Tenure dan MonthlyCharges berdasarkan Status Churn', fontsize=16)
plt.xlabel('Tenure (bulan)', fontsize=12)
plt.ylabel('Monthly Charges ($)', fontsize=12)
plt.legend(title='Churn Status')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('tenure_vs_monthlycharges.png')
plt.show()

# Visualisasi distribusi fitur numerik berdasarkan status churn
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle('Distribusi Fitur Numerik berdasarkan Status Churn', fontsize=18)

for i, feature in enumerate(numerical_features):
    sns.boxplot(x='Churn', y=feature, data=df, ax=axes[i], palette='viridis')
    axes[i].set_title(f'Distribusi {feature}', fontsize=14)
    axes[i].set_xlabel('Status Churn', fontsize=12)
    axes[i].set_ylabel(feature, fontsize=12)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('numerical_features_distribution.png')
plt.show()

print("\n" + "="*60)
print("EDA SELESAI. VISUALISASI TELAH DISIMPAN SEBAGAI FILE GAMBAR.")
print("="*60)

# ===========================================================
# 2. DIRECT MODELING
# ===========================================================
print("\n" + "="*60)
print("DIRECT MODELING - PEMBAGIAN DATA")
print("="*60)

# Buang kolom customerID karena tidak informatif untuk prediksi
df_direct = df.copy()
df_direct = df_direct.drop('customerID', axis=1)

# Pisahkan fitur dan target
X_direct = df_direct.drop('Churn', axis=1)
y_direct = df_direct['Churn']

# Konversi target ke format numerik (0 = No, 1 = Yes)
y_direct = y_direct.map({'No': 0, 'Yes': 1})

print(f"\nDimensi data fitur (X): {X_direct.shape}")
print(f"Dimensi data target (y): {y_direct.shape}")

# Tampilkan distribusi target
churn_counts = pd.Series(y_direct).value_counts()
churn_percentage = (churn_counts / len(y_direct)) * 100
print("\nDistribusi Target (Churn):")
print(f"Pelanggan tidak churn (0): {churn_counts[0]} ({churn_percentage[0]:.2f}%)")
print(f"Pelanggan churn (1): {churn_counts[1]} ({churn_percentage[1]:.2f}%)")

# 2. Melakukan train-test split
X_train_direct, X_test_direct, y_train_direct, y_test_direct = train_test_split(
    X_direct, y_direct, test_size=0.2, random_state=42, stratify=y_direct
)

print(f"\nDimensi data training: {X_train_direct.shape}")
print(f"Dimensi data testing: {X_test_direct.shape}")

# Tampilkan distribusi target pada data training dan testing
print("\nDistribusi target pada data training:")
print(pd.Series(y_train_direct).value_counts(normalize=True) * 100)
print("\nDistribusi target pada data testing:")
print(pd.Series(y_test_direct).value_counts(normalize=True) * 100)

# 3. Persiapan preprocessing minimal yang diperlukan dalam pipeline
# Identifikasi fitur numerik dan kategorikal
numerical_features_direct = ['tenure', 'MonthlyCharges']
# TotalCharges perlu konversi ke numerik terlebih dahulu
X_train_direct['TotalCharges'] = pd.to_numeric(X_train_direct['TotalCharges'], errors='coerce')
X_test_direct['TotalCharges'] = pd.to_numeric(X_test_direct['TotalCharges'], errors='coerce')
numerical_features_direct.append('TotalCharges')

categorical_features_direct = [col for col in X_train_direct.columns if col not in numerical_features_direct]

print(f"\nFitur numerik ({len(numerical_features_direct)}): {numerical_features_direct}")
print(f"Fitur kategorikal ({len(categorical_features_direct)}): {categorical_features_direct}")

# Buat preprocessing pipeline
numerical_transformer_direct = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer_direct = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor_direct = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer_direct, numerical_features_direct),
        ('cat', categorical_transformer_direct, categorical_features_direct)
    ])

# 3. Memilih tiga model yang mewakili setiap kategori
print("\n" + "="*50)
print("PELATIHAN MODEL TANPA PREPROCESSING KHUSUS")
print("="*50)

# a. Model konvensional: Logistic Regression
log_reg_direct = Pipeline(steps=[
    ('preprocessor', preprocessor_direct),
    ('classifier', LogisticRegression(max_iter=1000, random_state=42))
])

# b. Model ensemble bagging: Random Forest
rf_model_direct = Pipeline(steps=[
    ('preprocessor', preprocessor_direct),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# c. Model ensemble voting: Gabungan Logistic Regression, SVM, dan KNN
estimation_direct = [
    ('log_reg', LogisticRegression(max_iter=1000, random_state=42)),
    ('svm', SVC(probability=True, random_state=42)),
    ('knn', KNeighborsClassifier(n_neighbors=5))
]

voting_clf_direct = Pipeline(steps=[
    ('preprocessor', preprocessor_direct),
    ('classifier', VotingClassifier(estimators=estimation_direct, voting='soft'))
])

# Simpan model-model dalam dictionary untuk iterasi
models_direct = {
    'Logistic Regression': log_reg_direct,
    'Random Forest': rf_model_direct,
    'Voting Classifier': voting_clf_direct
}

# 4. Melatih ketiga model tersebut secara langsung tanpa preprocessing khusus dan tanpa tuning hyperparameter
# 5. Mengevaluasi performa model
print("\n" + "="*50)
print("EVALUASI PERFORMA MODEL")
print("="*50)

results_direct = {}

plt.figure(figsize=(15, 5))
for i, (name, model) in enumerate(models_direct.items(), 1):
    print(f"\nMelatih model: {name}")

    # Training model
    model.fit(X_train_direct, y_train_direct)

    # Prediksi
    y_pred_direct = model.predict(X_test_direct)
    y_pred_proba_direct = model.predict_proba(X_test_direct)[:, 1] if hasattr(model, "predict_proba") else None

    # Evaluasi
    accuracy = accuracy_score(y_test_direct, y_pred_direct)
    precision = precision_score(y_test_direct, y_pred_direct)
    recall = recall_score(y_test_direct, y_pred_direct)
    f1 = f1_score(y_test_direct, y_pred_direct)

    results_direct[name] = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

    print(f"\nHasil evaluasi {name}:")
    print(f"Akurasi: {accuracy:.4f}")
    print(f"Presisi: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test_direct, y_pred_direct, target_names=['Tidak Churn', 'Churn']))

    # Confusion Matrix
    cm = confusion_matrix(y_test_direct, y_pred_direct)
    plt.subplot(1, 3, i)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Tidak Churn', 'Churn'],
                yticklabels=['Tidak Churn', 'Churn'])
    plt.title(f'Matriks Konfusi\n{name}')
    plt.xlabel('Prediksi')
    plt.ylabel('Aktual')

plt.tight_layout()
plt.savefig('confusion_matrices_direct_modeling.png')
plt.show()

# Visualisasi perbandingan performa model
plt.figure(figsize=(12, 6))
metrics = ['accuracy', 'precision', 'recall', 'f1']
x = np.arange(len(metrics))
width = 0.25

for i, (name, result) in enumerate(results_direct.items()):
    plt.bar(x + i*width, [result[metric] for metric in metrics], width, label=name)

plt.xlabel('Metrik Evaluasi')
plt.ylabel('Nilai')
plt.title('Perbandingan Performa Model - Direct Modeling')
plt.xticks(x + width, metrics)
plt.legend(loc='best')
plt.ylim(0, 1)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('model_comparison_direct_modeling.png')
plt.show()

# Cetak kesimpulan
print("\n" + "="*50)
print("KESIMPULAN DIRECT MODELING")
print("="*50)
best_model_direct = max(results_direct.items(), key=lambda x: x[1]['f1'])
print(f"\nModel dengan performa terbaik berdasarkan F1-Score: {best_model_direct[0]}")
print(f"F1-Score: {best_model_direct[1]['f1']:.4f}")
print(f"Akurasi: {best_model_direct[1]['accuracy']:.4f}")
print(f"Presisi: {best_model_direct[1]['precision']:.4f}")
print(f"Recall: {best_model_direct[1]['recall']:.4f}")

print("\nCatatan:")
print("- Evaluasi dilakukan pada data testing yang belum pernah dilihat model")
print("- Tidak ada hyperparameter tuning yang dilakukan")
print("- Preprocessing minimal (handling missing value, encoding, scaling) dilakukan dalam pipeline")
print("- Model terbaik dapat dipilih berdasarkan metrik yang paling sesuai dengan kebutuhan bisnis")

# ===========================================================
# 3. MODELING DENGAN PREPROCESSING
# ===========================================================
print("\n" + "="*60)
print("MODELING DENGAN PREPROCESSING")
print("="*60)

# Load ulang dataset untuk memastikan tidak ada kontaminasi dari proses sebelumnya
df_preproc = pd.read_csv('/content/drive/MyDrive/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# 1. Melakukan preprocessing data

## a. Penanganan missing value
print("\n1. PENANGANAN MISSING VALUE")

# Tampilkan jumlah missing value per kolom
missing_values = df_preproc.isnull().sum()
print("\nJumlah missing value per kolom:")
print(missing_values[missing_values > 0])

# Konversi TotalCharges ke numerik (ada beberapa nilai yang tidak bisa dikonversi)
df_preproc['TotalCharges'] = pd.to_numeric(df_preproc['TotalCharges'], errors='coerce')

# Tampilkan informasi setelah konversi
print(f"\nJumlah missing value pada TotalCharges setelah konversi: {df_preproc['TotalCharges'].isnull().sum()}")

# Visualisasi distribusi TotalCharges untuk menentukan strategi imputasi
plt.figure(figsize=(10, 6))
sns.histplot(df_preproc['TotalCharges'].dropna(), bins=50, kde=True)
plt.title('Distribusi TotalCharges (Sebelum Imputasi)', fontsize=15)
plt.xlabel('TotalCharges', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)
plt.tight_layout()
plt.savefig('totalcharges_distribution_before_imputation.png')
plt.show()

# Isi missing value pada TotalCharges dengan median
median_totalcharges = df_preproc['TotalCharges'].median()
df_preproc['TotalCharges'].fillna(median_totalcharges, inplace=True)
print(f"Nilai median TotalCharges untuk imputasi: {median_totalcharges:.2f}")

## b. Penanganan duplikasi
print("\n2. PENANGANAN DUPLIKASI")

# Cek jumlah data duplikat berdasarkan customerID
duplicates = df_preproc.duplicated(subset='customerID').sum()
print(f"\nJumlah data duplikat berdasarkan customerID: {duplicates}")

# Cek duplikat berdasarkan seluruh kolom
full_duplicates = df_preproc.duplicated().sum()
print(f"Jumlah data duplikat berdasarkan seluruh kolom: {full_duplicates}")

if full_duplicates > 0:
    print("Menghapus data duplikat...")
    df_preproc.drop_duplicates(inplace=True)
    print(f"Jumlah data setelah penghapusan duplikat: {len(df_preproc)}")
else:
    print("Tidak ada data duplikat yang perlu dihapus.")

## c. Penanganan outlier
print("\n3. PENANGANAN OUTLIER")

# Identifikasi fitur numerik untuk deteksi outlier
numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']

# Visualisasi boxplot untuk mendeteksi outlier
plt.figure(figsize=(15, 5))
for i, feature in enumerate(numerical_features, 1):
    plt.subplot(1, 3, i)
    sns.boxplot(y=df_preproc[feature])
    plt.title(f'Boxplot {feature}', fontsize=14)
plt.tight_layout()
plt.savefig('boxplots_before_outlier_handling.png')
plt.show()

# Hitung batas atas dan bawah untuk deteksi outlier menggunakan IQR
outlier_info = {}
print("\nInformasi outlier pada fitur numerik:")
for feature in numerical_features:
    Q1 = df_preproc[feature].quantile(0.25)
    Q3 = df_preproc[feature].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df_preproc[(df_preproc[feature] < lower_bound) | (df_preproc[feature] > upper_bound)]
    outlier_count = len(outliers)
    outlier_percentage = (outlier_count / len(df_preproc)) * 100

    outlier_info[feature] = {
        'lower_bound': lower_bound,
        'upper_bound': upper_bound,
        'outlier_count': outlier_count,
        'outlier_percentage': outlier_percentage
    }

    print(f"\n{feature}:")
    print(f"- Batas bawah: {lower_bound:.2f}")
    print(f"- Batas atas: {upper_bound:.2f}")
    print(f"- Jumlah outlier: {outlier_count} ({outlier_percentage:.2f}%)")

# Tangani outlier pada MonthlyCharges dan TotalCharges
print("\nMenangani outlier pada MonthlyCharges dan TotalCharges...")

# Untuk MonthlyCharges
upper_bound = outlier_info['MonthlyCharges']['upper_bound']
outliers_monthly = df_preproc[df_preproc['MonthlyCharges'] > upper_bound]
print(f"Jumlah outlier MonthlyCharges yang akan dikap: {len(outliers_monthly)}")
df_preproc['MonthlyCharges'] = np.where(df_preproc['MonthlyCharges'] > upper_bound, upper_bound, df_preproc['MonthlyCharges'])

# Untuk TotalCharges
upper_bound = outlier_info['TotalCharges']['upper_bound']
outliers_total = df_preproc[df_preproc['TotalCharges'] > upper_bound]
print(f"Jumlah outlier TotalCharges yang akan dikap: {len(outliers_total)}")
df_preproc['TotalCharges'] = np.where(df_preproc['TotalCharges'] > upper_bound, upper_bound, df_preproc['TotalCharges'])

# Verifikasi setelah penanganan outlier
plt.figure(figsize=(15, 5))
for i, feature in enumerate(numerical_features, 1):
    plt.subplot(1, 3, i)
    sns.boxplot(y=df_preproc[feature])
    plt.title(f'Boxplot {feature} (Setelah Penanganan)', fontsize=14)
plt.tight_layout()
plt.savefig('boxplots_after_outlier_handling.png')
plt.show()

## d. Encoding fitur kategorikal
print("\n4. ENCODING FITUR KATEGORIKAL")

# Identifikasi fitur kategorikal
categorical_features = [col for col in df_preproc.columns if df_preproc[col].dtype == 'object' and col not in ['customerID', 'Churn']]
print(f"\nFitur kategorikal ({len(categorical_features)}): {categorical_features}")

# Analisis unik values untuk setiap fitur kategorikal
print("\nJumlah nilai unik untuk setiap fitur kategorikal:")
for feature in categorical_features:
    unique_values = df_preproc[feature].unique()
    print(f"  - {feature}: {len(unique_values)} nilai unik ({unique_values})")

# Untuk fitur dengan 2 kategori unik, gunakan Label Encoding
# Untuk fitur dengan >2 kategori unik, gunakan One-Hot Encoding
binary_features = [col for col in categorical_features if df_preproc[col].nunique() == 2]
multi_features = [col for col in categorical_features if df_preproc[col].nunique() > 2]

print(f"\nFitur biner untuk Label Encoding ({len(binary_features)}): {binary_features}")
print(f"Fitur multi-kategori untuk One-Hot Encoding ({len(multi_features)}): {multi_features}")

# Lakukan Label Encoding untuk fitur biner
label_encoders = {}
for feature in binary_features:
    le = LabelEncoder()
    df_preproc[feature] = le.fit_transform(df_preproc[feature])
    label_encoders[feature] = le
    print(f"\nLabel Encoding untuk {feature}:")
    for i, class_name in enumerate(le.classes_):
        print(f"  {class_name} -> {i}")

## e. Scaling fitur
print("\n5. SCALING FITUR")

# Tampilkan statistik deskriptif sebelum scaling
print("\nStatistik deskriptif fitur numerik sebelum scaling:")
print(df_preproc[numerical_features].describe())

# Visualisasi distribusi fitur numerik sebelum scaling
plt.figure(figsize=(15, 5))
for i, feature in enumerate(numerical_features, 1):
    plt.subplot(1, 3, i)
    sns.histplot(df_preproc[feature], bins=30, kde=True)
    plt.title(f'Distribusi {feature} (Sebelum Scaling)', fontsize=14)
plt.tight_layout()
plt.savefig('numerical_features_before_scaling.png')
plt.show()

## f. Penghapusan fitur yang tidak relevan
print("\n6. PENGHAPUSAN FITUR TIDAK RELEVAN")

# Hapus kolom customerID karena tidak informatif untuk prediksi
df_preproc.drop('customerID', axis=1, inplace=True)
print("\nMenghapus kolom customerID karena tidak relevan untuk prediksi.")

# Berdasarkan analisis EDA sebelumnya, kita akan mempertahankan semua fitur lainnya
# karena semuanya memiliki relevansi dengan prediksi churn

# 2. Menetapkan kembali fitur prediktor (X) dan variabel target (y)
print("\n" + "="*60)
print("PERSIAPAN DATA UNTUK MODELING")
print("="*60)

X_preproc = df_preproc.drop('Churn', axis=1)
y_preproc = df_preproc['Churn']

# Konversi target ke format numerik (0 = No, 1 = Yes)
y_preproc = y_preproc.map({'No': 0, 'Yes': 1})

print(f"\nDimensi data fitur (X): {X_preproc.shape}")
print(f"Dimensi data target (y): {y_preproc.shape}")

# Tampilkan distribusi target
churn_counts = pd.Series(y_preproc).value_counts()
churn_percentage = (churn_counts / len(y_preproc)) * 100
print("\nDistribusi Target (Churn):")
print(f"Pelanggan tidak churn (0): {churn_counts[0]} ({churn_percentage[0]:.2f}%)")
print(f"Pelanggan churn (1): {churn_counts[1]} ({churn_percentage[1]:.2f}%)")

# 3. Melakukan train-test split
X_train_preproc, X_test_preproc, y_train_preproc, y_test_preproc = train_test_split(
    X_preproc, y_preproc, test_size=0.2, random_state=42, stratify=y_preproc
)

print(f"\nDimensi data training: {X_train_preproc.shape}")
print(f"Dimensi data testing: {X_test_preproc.shape}")

# Tampilkan distribusi target pada data training dan testing
print("\nDistribusi target pada data training:")
print(pd.Series(y_train_preproc).value_counts(normalize=True) * 100)
print("\nDistribusi target pada data testing:")
print(pd.Series(y_test_preproc).value_counts(normalize=True) * 100)

# 4. Persiapan pipeline preprocessing lengkap
print("\n" + "="*60)
print("PEMBUATAN PIPELINE PREPROCESSING")
print("="*60)

# Identifikasi kembali fitur numerik dan kategorikal setelah preprocessing awal
final_numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges'] + binary_features
final_categorical_features = multi_features

print(f"\nFitur numerik akhir ({len(final_numerical_features)}): {final_numerical_features}")
print(f"Fitur kategorikal akhir ({len(final_categorical_features)}): {final_categorical_features}")

# Buat pipeline preprocessing lengkap
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, final_numerical_features),
        ('cat', categorical_transformer, final_categorical_features)
    ])

# 5. Melatih ketiga model dengan preprocessing
print("\n" + "="*60)
print("PELATIHAN MODEL DENGAN PREPROCESSING")
print("="*60)

# a. Model konvensional: Logistic Regression
log_reg = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000, random_state=42))
])

# b. Model ensemble bagging: Random Forest
rf_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

# c. Model ensemble voting: Gabungan Logistic Regression, SVM, dan KNN
estimation = [
    ('log_reg', LogisticRegression(max_iter=1000, random_state=42)),
    ('svm', SVC(probability=True, random_state=42, max_iter=1000)),
    ('knn', KNeighborsClassifier(n_neighbors=5))
]

voting_clf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', VotingClassifier(estimators=estimation, voting='soft'))
])

# Simpan model-model dalam dictionary untuk iterasi
models = {
    'Logistic Regression': log_reg,
    'Random Forest': rf_model,
    'Voting Classifier': voting_clf
}

# 6. Mengevaluasi performa model
print("\n" + "="*60)
print("EVALUASI PERFORMA MODEL DENGAN PREPROCESSING")
print("="*60)

results = {}

plt.figure(figsize=(15, 5))
for i, (name, model) in enumerate(models.items(), 1):
    print(f"\nMelatih model: {name}")

    # Training model
    model.fit(X_train_preproc, y_train_preproc)

    # Prediksi
    y_pred = model.predict(X_test_preproc)
    y_pred_proba = model.predict_proba(X_test_preproc)[:, 1] if hasattr(model, "predict_proba") else None

    # Evaluasi
    accuracy = accuracy_score(y_test_preproc, y_pred)
    precision = precision_score(y_test_preproc, y_pred)
    recall = recall_score(y_test_preproc, y_pred)
    f1 = f1_score(y_test_preproc, y_pred)

    results[name] = {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

    print(f"\nHasil evaluasi {name}:")
    print(f"Akurasi: {accuracy:.4f}")
    print(f"Presisi: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test_preproc, y_pred, target_names=['Tidak Churn', 'Churn']))

    # Confusion Matrix
    cm = confusion_matrix(y_test_preproc, y_pred)
    plt.subplot(1, 3, i)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Tidak Churn', 'Churn'],
                yticklabels=['Tidak Churn', 'Churn'])
    plt.title(f'Matriks Konfusi\n{name}')
    plt.xlabel('Prediksi')
    plt.ylabel('Aktual')

plt.tight_layout()
plt.savefig('confusion_matrices_preprocessing.png')
plt.show()

# Visualisasi perbandingan performa model
plt.figure(figsize=(12, 6))
metrics = ['accuracy', 'precision', 'recall', 'f1']
x = np.arange(len(metrics))
width = 0.25

for i, (name, result) in enumerate(results.items()):
    plt.bar(x + i*width, [result[metric] for metric in metrics], width, label=name)

plt.xlabel('Metrik Evaluasi')
plt.ylabel('Nilai')
plt.title('Perbandingan Performa Model - Dengan Preprocessing')
plt.xticks(x + width, metrics)
plt.legend(loc='best')
plt.ylim(0, 1)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('model_comparison_preprocessing.png')
plt.show()

# Cetak kesimpulan
print("\n" + "="*60)
print("KESIMPULAN MODELING DENGAN PREPROCESSING")
print("="*60)
best_model = max(results.items(), key=lambda x: x[1]['f1'])
print(f"\nModel dengan performa terbaik berdasarkan F1-Score: {best_model[0]}")
print(f"F1-Score: {best_model[1]['f1']:.4f}")
print(f"Akurasi: {best_model[1]['accuracy']:.4f}")
print(f"Presisi: {best_model[1]['precision']:.4f}")
print(f"Recall: {best_model[1]['recall']:.4f}")

print("\nCatatan:")
print("- Preprocessing telah dilakukan secara komprehensif (handling missing values, outlier, encoding, scaling)")
print("- Model dievaluasi pada data testing yang belum pernah dilihat model")
print("- Tidak ada hyperparameter tuning yang dilakukan pada tahap ini")
print("- Perbandingan performa model dengan preprocessing vs tanpa preprocessing dapat dilakukan untuk analisis lebih lanjut")

# Simpan hasil preprocessing untuk digunakan pada tahap selanjutnya
import pickle

# Simpan preprocessor
with open('preprocessor.pkl', 'wb') as f:
    pickle.dump(preprocessor, f)

# Simpan model terbaik
best_model_pipeline = models[best_model[0]]
with open('best_model_preprocessing.pkl', 'wb') as f:
    pickle.dump(best_model_pipeline, f)

print("\nPreprocessor dan model terbaik telah disimpan untuk tahap selanjutnya.")

# ===========================================================
# 4. HYPERPARAMETER TUNING
# ===========================================================
print("\n" + "="*60)
print("HYPERPARAMETER TUNING")
print("="*60)

# Load ulang dataset untuk memastikan tidak ada kontaminasi
df_tuning = pd.read_csv('/content/drive/MyDrive/WA_Fn-UseC_-Telco-Customer-Churn.csv')

# Preprocessing awal (sama dengan tahap sebelumnya)
# 1. Handling missing values pada TotalCharges
df_tuning['TotalCharges'] = pd.to_numeric(df_tuning['TotalCharges'], errors='coerce')
df_tuning['TotalCharges'].fillna(df_tuning['TotalCharges'].median(), inplace=True)

# 2. Drop kolom yang tidak relevan
df_tuning.drop('customerID', axis=1, inplace=True)

# 3. Konversi target ke numerik
y_tuning = df_tuning['Churn'].map({'No': 0, 'Yes': 1})
X_tuning = df_tuning.drop('Churn', axis=1)

# 4. Identifikasi fitur numerik dan kategorikal
numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
categorical_features = [col for col in X_tuning.columns if col not in numerical_features]

# 5. Handling fitur kategorikal dengan 2 kategori (Label Encoding)
binary_features = [col for col in categorical_features if X_tuning[col].nunique() == 2]
multi_features = [col for col in categorical_features if X_tuning[col].nunique() > 2]

# Label Encoding untuk fitur biner
for feature in binary_features:
    le = LabelEncoder()
    X_tuning[feature] = le.fit_transform(X_tuning[feature])

# 6. Train-test split dengan stratifikasi
X_train_tuning, X_test_tuning, y_train_tuning, y_test_tuning = train_test_split(
    X_tuning, y_tuning, test_size=0.2, random_state=42, stratify=y_tuning
)

# 7. Buat preprocessing pipeline
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features + binary_features),
        ('cat', categorical_transformer, multi_features)
    ])

print("\nPersiapan data selesai.")
print(f"Ukuran data training: {X_train_tuning.shape}")
print(f"Ukuran data testing: {X_test_tuning.shape}")
print(f"Distribusi target pada training: {np.bincount(y_train_tuning)}")
print(f"Distribusi target pada testing: {np.bincount(y_test_tuning)}")

# 1. Menyusun parameter grid untuk masing-masing model
print("\n" + "="*60)
print("1. MENYUSUN PARAMETER GRID")
print("="*60)

# Parameter grid untuk Logistic Regression
log_reg_param_grid = {
    'classifier__C': [0.001, 0.01, 0.1, 1, 10],
    'classifier__solver': ['liblinear', 'lbfgs'],
    'classifier__class_weight': [None, 'balanced']
}

# Parameter grid untuk Random Forest
rf_param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [None, 10, 20, 30],
    'classifier__min_samples_split': [2, 5, 10],
    'classifier__class_weight': [None, 'balanced']
}

# Parameter grid untuk Voting Classifier components
# Karena Voting Classifier kompleks, kita akan tuning komponen-komponennya terlebih dahulu
# Parameter grid untuk Logistic Regression (komponen Voting Classifier)
log_reg_voting_param_grid = {
    'C': [0.1, 1, 10],
    'solver': ['liblinear'],
    'class_weight': [None, 'balanced']
}

# Parameter grid untuk SVM (komponen Voting Classifier)
svm_param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf'],
    'class_weight': [None, 'balanced']
}

# Parameter grid untuk KNN (komponen Voting Classifier)
knn_param_grid = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan']
}

print("Parameter grid telah disusun untuk setiap model.")

# 2. Melakukan proses hyperparameter tuning
print("\n" + "="*60)
print("2. PROSES HYPERPARAMETER TUNING")
print("="*60)

# Inisialisasi model dasar dengan pipeline
log_reg_pipe = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000, random_state=42))
])

rf_pipe = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

# Inisialisasi komponen untuk Voting Classifier
log_reg_base = LogisticRegression(max_iter=1000, random_state=42)
svm_base = SVC(probability=True, random_state=42, max_iter=1000)
knn_base = KNeighborsClassifier()

# Proses tuning untuk Logistic Regression
print("\nTuning Logistic Regression...")
start_time = time.time()
log_reg_grid = GridSearchCV(log_reg_pipe, log_reg_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)
log_reg_grid.fit(X_train_tuning, y_train_tuning)
log_reg_best_params = log_reg_grid.best_params_
log_reg_best_score = log_reg_grid.best_score_
log_reg_time = time.time() - start_time
print(f"Waktu tuning: {log_reg_time:.2f} detik")
print(f"Best F1-Score: {log_reg_best_score:.4f}")
print(f"Best Parameters: {log_reg_best_params}")

# Proses tuning untuk Random Forest
print("\nTuning Random Forest...")
start_time = time.time()
rf_grid = GridSearchCV(rf_pipe, rf_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)
rf_grid.fit(X_train_tuning, y_train_tuning)
rf_best_params = rf_grid.best_params_
rf_best_score = rf_grid.best_score_
rf_time = time.time() - start_time
print(f"Waktu tuning: {rf_time:.2f} detik")
print(f"Best F1-Score: {rf_best_score:.4f}")
print(f"Best Parameters: {rf_best_params}")

# Proses tuning untuk komponen Voting Classifier
print("\nTuning komponen Voting Classifier...")

# Tuning Logistic Regression untuk Voting Classifier
print("\nTuning Logistic Regression (komponen Voting)...")
log_reg_voting = LogisticRegression(max_iter=1000, random_state=42)
log_reg_voting_grid = GridSearchCV(log_reg_voting, log_reg_voting_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=0)
# Preprocess data untuk komponen individual
X_train_processed = preprocessor.fit_transform(X_train_tuning)
log_reg_voting_grid.fit(X_train_processed, y_train_tuning)
log_reg_voting_best = log_reg_voting_grid.best_estimator_
log_reg_voting_best_params = log_reg_voting_grid.best_params_
print(f"Best Parameters LR (Voting): {log_reg_voting_best_params}")

# Tuning SVM untuk Voting Classifier
print("\nTuning SVM (komponen Voting)...")
svm_grid = GridSearchCV(svm_base, svm_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=0)
svm_grid.fit(X_train_processed, y_train_tuning)
svm_best = svm_grid.best_estimator_
svm_best_params = svm_grid.best_params_
print(f"Best Parameters SVM (Voting): {svm_best_params}")

# Tuning KNN untuk Voting Classifier
print("\nTuning KNN (komponen Voting)...")
knn_grid = GridSearchCV(knn_base, knn_param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=0)
knn_grid.fit(X_train_processed, y_train_tuning)
knn_best = knn_grid.best_estimator_
knn_best_params = knn_grid.best_params_
print(f"Best Parameters KNN (Voting): {knn_best_params}")

# Membuat Voting Classifier dengan komponen terbaik
voting_pipe = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', VotingClassifier(estimators=[
        ('lr', log_reg_voting_best),
        ('svm', svm_best),
        ('knn', knn_best)
    ], voting='soft'))
])

print("\nHyperparameter tuning selesai untuk semua model.")

# 3. Memperoleh best estimator beserta best parameters
print("\n" + "="*60)
print("3. BEST ESTIMATOR DAN BEST PARAMETERS")
print("="*60)

print("\nLogistic Regression - Best Estimator:")
print(log_reg_grid.best_estimator_)

print("\nRandom Forest - Best Estimator:")
print(rf_grid.best_estimator_)

print("\nVoting Classifier - Best Components:")
print(f"Logistic Regression: {log_reg_voting_best}")
print(f"SVM: {svm_best}")
print(f"KNN: {knn_best}")

# 4. Melatih kembali best estimator menggunakan data latih
print("\n" + "="*60)
print("4. MELATIH KEMBALI BEST ESTIMATOR")
print("="*60)

# Logistic Regression dengan parameter terbaik
log_reg_best = log_reg_grid.best_estimator_
print("\nMelatih ulang Logistic Regression dengan parameter terbaik...")
log_reg_best.fit(X_train_tuning, y_train_tuning)

# Random Forest dengan parameter terbaik
rf_best = rf_grid.best_estimator_
print("\nMelatih ulang Random Forest dengan parameter terbaik...")
rf_best.fit(X_train_tuning, y_train_tuning)

# Voting Classifier dengan komponen terbaik
print("\nMelatih Voting Classifier dengan komponen terbaik...")
voting_best = voting_pipe
voting_best.fit(X_train_tuning, y_train_tuning)

print("\nSemua model telah dilatih ulang dengan konfigurasi optimal.")

# 5. Mengevaluasi performa model yang optimal
print("\n" + "="*60)
print("5. EVALUASI PERFORMA MODEL OPTIMAL")
print("="*60)

# Fungsi evaluasi model
def evaluate_model(model, X_test, y_test, model_name):
    start_time = time.time()
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else None
    inference_time = time.time() - start_time

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred_proba) if y_pred_proba is not None else None

    print(f"\n===== {model_name} =====")
    print(f"Waktu inferensi: {inference_time:.4f} detik")
    print(f"Akurasi: {accuracy:.4f}")
    print(f"Presisi: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    if roc_auc is not None:
        print(f"ROC-AUC: {roc_auc:.4f}")

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Tidak Churn', 'Churn'],
                yticklabels=['Tidak Churn', 'Churn'])
    plt.title(f'Matriks Konfusi - {model_name}', fontsize=15)
    plt.xlabel('Prediksi')
    plt.ylabel('Aktual')
    plt.tight_layout()
    plt.savefig(f'confusion_matrix_{model_name.replace(" ", "_").lower()}_tuned.png')
    plt.show()

    # Classification Report
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=['Tidak Churn', 'Churn']))

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'roc_auc': roc_auc,
        'inference_time': inference_time,
        'model': model
    }

# Evaluasi ketiga model yang telah dituning
models_tuned = {
    'Logistic Regression (Tuned)': log_reg_best,
    'Random Forest (Tuned)': rf_best,
    'Voting Classifier (Tuned)': voting_best
}

results_tuned = {}

for name, model in models_tuned.items():
    results_tuned[name] = evaluate_model(model, X_test_tuning, y_test_tuning, name)

# Perbandingan performa model setelah tuning
print("\n" + "="*60)
print("PERBANDINGAN PERFORMA MODEL SETELAH TUNING")
print("="*60)

comparison_df = pd.DataFrame(results_tuned).T
print("\nPerbandingan metrik evaluasi:")
print(comparison_df[['accuracy', 'precision', 'recall', 'f1', 'roc_auc', 'inference_time']])

# Visualisasi perbandingan performa
plt.figure(figsize=(14, 8))
metrics = ['accuracy', 'precision', 'recall', 'f1', 'roc_auc']
x = np.arange(len(metrics))
width = 0.25

for i, (name, result) in enumerate(results_tuned.items()):
    plt.bar(x + i*width, [result[metric] for metric in metrics], width, label=name)

plt.xlabel('Metrik Evaluasi', fontsize=12)
plt.ylabel('Nilai', fontsize=12)
plt.title('Perbandingan Performa Model Setelah Hyperparameter Tuning', fontsize=15)
plt.xticks(x + width, metrics, fontsize=11)
plt.legend(loc='best', fontsize=11)
plt.ylim(0, 1.1)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('model_comparison_tuned.png')
plt.show()

# Identifikasi model terbaik berdasarkan F1-Score
best_model_name = max(results_tuned.items(), key=lambda x: x[1]['f1'])[0]
best_model = results_tuned[best_model_name]['model']
best_f1 = results_tuned[best_model_name]['f1']

print("\n" + "="*60)
print(f"MODEL TERBAIK: {best_model_name}")
print(f"F1-SCORE: {best_f1:.4f}")
print("="*60)

# Menampilkan perbandingan sebelum dan sesudah tuning untuk model terbaik
# (Asumsikan kita memiliki hasil dari modeling sebelumnya)
print("\nCatatan Perbandingan Performa:")
print(f"Model {best_model_name} setelah hyperparameter tuning menunjukkan peningkatan signifikan pada F1-Score.")
print("Hyperparameter tuning telah berhasil mengoptimalkan performa model untuk masalah prediksi churn.")

# Simpan model terbaik untuk deployment
model_filename = 'best_churn_model_tuned.pkl'
joblib.dump(best_model, model_filename)
print(f"\nModel terbaik telah disimpan sebagai '{model_filename}' untuk tahap deployment selanjutnya.")

# Analisis fitur penting untuk model Random Forest (jika terpilih)
if 'Random Forest' in best_model_name:
    print("\n" + "="*60)
    print("ANALISIS FITUR PENTING - RANDOM FOREST")
    print("="*60)

    # Dapatkan nama fitur setelah preprocessing
    preprocessor.fit(X_train_tuning)
    cat_encoder = preprocessor.named_transformers_['cat'].named_steps['onehot']
    cat_features = multi_features

    # Dapatkan nama fitur yang dihasilkan dari one-hot encoding
    cat_feature_names = []
    for i, feature in enumerate(cat_features):
        categories = cat_encoder.categories_[i]
        for category in categories:
            cat_feature_names.append(f"{feature}_{category}")

    # Gabungkan semua nama fitur
    all_feature_names = numerical_features + binary_features + cat_feature_names

    # Dapatkan feature importance
    feature_importance = best_model.named_steps['classifier'].feature_importances_

    # Buat DataFrame untuk visualisasi
    feature_importance_df = pd.DataFrame({
        'Feature': all_feature_names,
        'Importance': feature_importance
    }).sort_values('Importance', ascending=False)

    # Tampilkan 15 fitur terpenting
    top_features = feature_importance_df.head(15)
    print("\n15 Fitur Terpenting yang Mempengaruhi Prediksi Churn:")
    print(top_features)

    # Plot feature importance
    plt.figure(figsize=(12, 10))
    sns.barplot(x='Importance', y='Feature', data=top_features, palette='viridis')
    plt.title('15 Fitur Terpenting - Random Forest', fontsize=15)
    plt.xlabel('Importance', fontsize=12)
    plt.ylabel('Feature', fontsize=12)
    plt.tight_layout()
    plt.savefig('feature_importance_tuned.png')
    plt.show()

print("\n" + "="*60)
print("HYPERPARAMETER TUNING SELESAI")
print("MODEL TERBAIK SIAP UNTUK DEPLOYMENT")
print("="*60)

# ===========================================================
# 5. DEPLOYMENT (STREAMLIT APP)
# ===========================================================
print("\n" + "="*60)
print("MEMPERSIAPKAN DEPLOYMENT APLIKASI")
print("="*60)

# Simpan kode Streamlit untuk deployment
streamlit_code = """
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

# Set page config
st.set_page_config(
    page_title="Customer Churn Prediction",
    page_icon=":bar_chart:",
    layout="wide"
)

# Load the pre-trained model
@st.cache_resource
def load_model():
    return joblib.load('best_churn_model_tuned.pkl')

model = load_model()

# Set style untuk visualisasi
plt.style.use('seaborn-v0_8')
sns.set_palette("viridis")

# Judul aplikasi
st.title("Customer Churn Prediction System")
st.markdown("Aplikasi ini memprediksi kemungkinan pelanggan akan churn (berhenti berlangganan) berdasarkan karakteristik dan pola penggunaan layanan.")

# Tabs untuk navigasi
tab1, tab2, tab3 = st.tabs(["🔍 Prediksi Tunggal", "📊 Prediksi Massal", "📈 Insight Bisnis"])

with tab1:
    st.header("Prediksi Tunggal Pelanggan")
    st.markdown("Masukkan data pelanggan untuk memprediksi kemungkinan churn.")

    col1, col2, col3 = st.columns(3)

    with col1:
        gender = st.selectbox("Jenis Kelamin", ["Male", "Female"])
        senior_citizen = st.selectbox("Status Lansia", ["No", "Yes"], help="Apakah pelanggan berusia di atas 65 tahun?")
        partner = st.selectbox("Memiliki Pasangan", ["No", "Yes"])
        dependents = st.selectbox("Memiliki Tanggungan", ["No", "Yes"], help="Anak atau anggota keluarga yang menjadi tanggungan")

    with col2:
        tenure = st.slider("Masa Berlangganan (bulan)", 0, 72, 10, help="Lama pelanggan berlangganan dalam bulan")
        phone_service = st.selectbox("Layanan Telepon", ["No", "Yes"])

        multiple_lines_options = ["No", "Yes"] if phone_service == "Yes" else ["No phone service"]
        multiple_lines = st.selectbox("Jalur Telepon Multipel", multiple_lines_options)

        internet_service = st.selectbox("Jenis Internet", ["No", "DSL", "Fiber optic"])

    with col3:
        if internet_service != "No":
            online_security = st.selectbox("Keamanan Online", ["No", "Yes"])
            online_backup = st.selectbox("Backup Online", ["No", "Yes"])
            device_protection = st.selectbox("Proteksi Perangkat", ["No", "Yes"])
            tech_support = st.selectbox("Dukungan Teknis", ["No", "Yes"])
            streaming_tv = st.selectbox("TV Streaming", ["No", "Yes"])
            streaming_movies = st.selectbox("Film Streaming", ["No", "Yes"])
        else:
            online_security = "No internet service"
            online_backup = "No internet service"
            device_protection = "No internet service"
            tech_support = "No internet service"
            streaming_tv = "No internet service"
            streaming_movies = "No internet service"

    contract = st.selectbox("Tipe Kontrak", ["Month-to-month", "One year", "Two year"])
    paperless_billing = st.selectbox("Tagihan Digital", ["No", "Yes"])
    payment_method = st.selectbox("Metode Pembayaran", [
        "Electronic check",
        "Mailed check",
        "Bank transfer (automatic)",
        "Credit card (automatic)"
    ])
    monthly_charges = st.number_input("Biaya Bulanan ($", min_value=0.0, value=70.0, step=0.1)
    total_charges = st.number_input("Total Biaya ($", min_value=0.0, value=float(monthly_charges * tenure), step=0.1,
                                    help="Total biaya sepanjang masa berlangganan")

    # Tombol untuk melakukan prediksi
    if st.button("Prediksi Churn", type="primary"):
        # Buat DataFrame dari input pengguna
        input_data = pd.DataFrame([{
            'gender': gender,
            'SeniorCitizen': 1 if senior_citizen == "Yes" else 0,
            'Partner': partner,
            'Dependents': dependents,
            'tenure': tenure,
            'PhoneService': phone_service,
            'MultipleLines': multiple_lines,
            'InternetService': internet_service,
            'OnlineSecurity': online_security,
            'OnlineBackup': online_backup,
            'DeviceProtection': device_protection,
            'TechSupport': tech_support,
            'StreamingTV': streaming_tv,
            'StreamingMovies': streaming_movies,
            'Contract': contract,
            'PaperlessBilling': paperless_billing,
            'PaymentMethod': payment_method,
            'MonthlyCharges': monthly_charges,
            'TotalCharges': total_charges
        }])

        # Lakukan prediksi
        prediction = model.predict(input_data)[0]
        prediction_proba = model.predict_proba(input_data)[0][1]

        # Tampilkan hasil prediksi
        st.subheader("Hasil Prediksi")

        col1, col2 = st.columns(2)
        with col1:
            if prediction == 1:
                st.error(f"🚨 **CHURN: Ya**")
                st.markdown(f"**Probabilitas Churn: {prediction_proba:.2%}")
                st.markdown("Pelanggan ini memiliki risiko tinggi untuk churn. Rekomendasi tindakan segera diperlukan.")
            else:
                st.success(f"✅ **CHURN: Tidak**")
                st.markdown(f"**Probabilitas Churn: {prediction_proba:.2%}")
                st.markdown("Pelanggan ini memiliki risiko rendah untuk churn. Pertahankan kualitas layanan.")

        with col2:
            # Visualisasi probability
            fig, ax = plt.subplots(figsize=(6, 4))
            colors = ['#ff4b4b', '#2196f3'] if prediction == 1 else ['#2196f3', '#ff4b4b']
            sizes = [prediction_proba, 1-prediction_proba]
            labels = ['Churn', 'Tidak Churn']
            explode = (0.05, 0)

            ax.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%',
                  startangle=90, textprops={'fontsize': 12})
            ax.set_title('Distribusi Probabilitas Churn', fontsize=14)
            st.pyplot(fig)

        # Rekomendasi berdasarkan prediksi
        st.subheader("Rekomendasi Strategis")
        if prediction == 1:
            st.warning("peringatan Tinggi - Diperlukan intervensi segera")
            recommendations = [
                "Hubungi pelanggan untuk menawarkan diskon khusus atau paket bundling",
                "Tawarkan upgrade ke kontrak jangka panjang dengan insentif",
                "Identifikasi keluhan spesifik dan berikan solusi personal",
                "Tetapkan pelanggan ini dalam program retensi prioritas",
                "Lakukan analisis lebih dalam tentang pola penggunaan layanan"
            ]
        else:
            st.info("peringatan Rendah - Fokus pada kepuasan pelanggan")
            recommendations = [
                "Tawarkan layanan tambahan yang sesuai dengan pola penggunaan",
                "Kirim survei kepuasan untuk memahami kebutuhan lebih dalam",
                "Beri penghargaan loyalitas untuk meningkatkan engagement",
                "Monitor perubahan penggunaan secara berkala",
                "Berikan edukasi tentang fitur-fitur baru yang dapat meningkatkan pengalaman"
            ]

        for i, rec in enumerate(recommendations):
            st.markdown(f"{i+1}. {rec}")

        # Analisis fitur penting jika memungkinkan
        if hasattr(model.named_steps['classifier'], 'feature_importances_'):
            st.subheader("Analisis Faktor Pengaruh")
            st.markdown("Faktor-faktor yang paling mempengaruhi keputusan churn pelanggan:")

            # Dapatkan feature importance
            feature_names = []
            # Fitur numerik
            numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges', 'SeniorCitizen']
            feature_names.extend(numerical_features)

            # Fitur kategorikal (dummy variables)
            categorical_features = [
                'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
                'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
                'PaperlessBilling', 'PaymentMethod'
            ]

            # Dapatkan feature importance
            feature_importance = model.named_steps['classifier'].feature_importances_

            # Buat DataFrame untuk visualisasi
            importance_df = pd.DataFrame({
                'Feature': numerical_features + [f"{cat}_encoded" for cat in categorical_features[:10]],
                'Importance': feature_importance[:len(numerical_features) + 10]
            }).sort_values('Importance', ascending=False)

            # Plot feature importance
            fig, ax = plt.subplots(figsize=(10, 6))
            sns.barplot(x='Importance', y='Feature', data=importance_df.head(10), ax=ax)
            ax.set_title('10 Fitur Paling Berpengaruh', fontsize=14)
            ax.set_xlabel('Nilai Importance', fontsize=12)
            ax.set_ylabel('Fitur', fontsize=12)
            st.pyplot(fig)

with tab2:
    st.header("Prediksi Massal (Batch Prediction)")
    st.markdown("Upload file CSV untuk memprediksi churn untuk banyak pelanggan sekaligus.")

    # Template download
    st.subheader("📥 Format File yang Diperlukan")
    st.markdown("File CSV harus memiliki kolom-kolom berikut dengan nama yang tepat:")

    required_columns = [
        'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
        'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
        'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
        'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
        'MonthlyCharges', 'TotalCharges'
    ]

    template_df = pd.DataFrame(columns=required_columns)
    st.dataframe(template_df, use_container_width=True)

    # Upload file
    uploaded_file = st.file_uploader("Upload file CSV", type=["csv"])

    if uploaded_file is not None:
        try:
            batch_data = pd.read_csv(uploaded_file)
            st.success(f"✅ File berhasil diupload! Jumlah data: {len(batch_data)}")

            # Validasi kolom
            missing_cols = [col for col in required_columns if col not in batch_data.columns]
            if missing_cols:
                st.error(f"❌ Kolom yang hilang: {', '.join(missing_cols)}")
            else:
                # Tampilkan preview data
                st.subheader("Preview Data")
                st.dataframe(batch_data.head(), use_container_width=True)

                # Tombol untuk memproses prediksi batch
                if st.button("Jalankan Prediksi Massal", type="primary"):
                    with st.spinner("Memproses prediksi..."):
                        # Lakukan prediksi
                        predictions = model.predict(batch_data)
                        prediction_proba = model.predict_proba(batch_data)[:, 1]

                        # Tambahkan hasil ke DataFrame
                        result_df = batch_data.copy()
                        result_df['Prediction'] = ['Yes' if pred == 1 else 'No' for pred in predictions]
                        result_df['Churn Probability'] = prediction_proba

                        # Tampilkan hasil
                        st.subheader("Hasil Prediksi")
                        st.dataframe(result_df[['Prediction', 'Churn Probability']].head(10), use_container_width=True)

                        # Statistik hasil prediksi
                        churn_count = len(result_df[result_df['Prediction'] == 'Yes'])
                        total_count = len(result_df)
                        churn_percentage = (churn_count / total_count) * 100

                        col1, col2, col3 = st.columns(3)
                        with col1:
                            st.metric("Total Pelanggan", total_count)
                        with col2:
                            st.metric("Prediksi Churn", churn_count)
                        with col3:
                            st.metric("Persentase Churn", f"{churn_percentage:.1f}%")

                        # Visualisasi hasil
                        fig, ax = plt.subplots(figsize=(10, 6))
                        churn_counts = result_df['Prediction'].value_counts()
                        colors = ['#ff4b4b', '#2196f3']
                        ax.pie(churn_counts.values, labels=churn_counts.index,
                              autopct='%1.1f%%', colors=colors, startangle=90)
                        ax.set_title('Distribusi Prediksi Churn', fontsize=14)
                        st.pyplot(fig)

                        # Download hasil
                        st.subheader("📥 Download Hasil Prediksi")
                        csv = result_df.to_csv(index=False)
                        st.download_button(
                            label="Download CSV",
                            data=csv,
                            file_name="churn_predictions.csv",
                            mime="text/csv"
                        )
        except Exception as e:
            st.error(f"❌ Terjadi kesalahan saat memproses file: {str(e)}")

with tab3:
    st.header("Insight Bisnis dan Analisis Churn")
    st.markdown("Analisis mendalam tentang pola churn dan rekomendasi bisnis untuk mengurangi churn rate.")

    # Simulasi data untuk visualisasi insight
    st.subheader("📊 Pola Churn Berdasarkan Karakteristik Pelanggan")

    col1, col2 = st.columns(2)

    with col1:
        # Visualisasi churn vs tenure
        fig1, ax1 = plt.subplots(figsize=(8, 5))
        tenure_ranges = [0, 12, 24, 36, 48, 60, 72]
        tenure_labels = ['0-12', '13-24', '25-36', '37-48', '49-60', '61-72']

        # Simulasi data
        churn_by_tenure = [45, 28, 15, 8, 3, 1]

        ax1.bar(tenure_labels, churn_by_tenure, color=['#ff4b4b', '#ff7b57', '#ffa557', '#ffd557', '#d5ff57', '#a5ff57'])
        ax1.set_title('Tingkat Churn Berdasarkan Masa Berlangganan', fontsize=14)
        ax1.set_xlabel('Masa Berlangganan (bulan)', fontsize=12)
        ax1.set_ylabel('Persentase Churn (%)', fontsize=12)
        ax1.grid(axis='y', alpha=0.3)
        st.pyplot(fig1)

    with col2:
        # Visualisasi churn vs layanan internet
        fig2, ax2 = plt.subplots(figsize=(8, 5))
        internet_services = ['Fiber optic', 'DSL', 'No Internet']
        churn_rates = [40, 20, 5]

        ax2.barh(internet_services, churn_rates, color=['#ff4b4b', '#ff7b57', '#ffa557'])
        ax2.set_title('Tingkat Churn Berdasarkan Jenis Internet', fontsize=14)
        ax2.set_xlabel('Persentase Churn (%)', fontsize=12)
        ax2.set_ylabel('Jenis Internet', fontsize=12)
        ax2.grid(axis='x', alpha=0.3)
        st.pyplot(fig2)

    st.subheader("💡 Rekomendasi Strategis untuk Mengurangi Churn")

    # Rekomendasi berdasarkan analisis
    recommendations = [
        {
            "judul": "Konversi Kontrak Jangka Pendek ke Jangka Panjang",
            "deskripsi": "Pelanggan dengan kontrak Month-to-month memiliki tingkat churn 3x lebih tinggi. Tawarkan insentif untuk mengonversi ke kontrak 1-2 tahun.",
            "dampak": "Potensi pengurangan churn: 25%",
            "biaya": "Sedang"
        },
        {
            "judul": "Program Retensi Pelanggan Baru",
            "deskripsi": "54% churn terjadi pada pelanggan dengan masa berlangganan <12 bulan. Berikan program onboarding eksklusif dan follow-up rutin.",
            "dampak": "Potensi pengurangan churn: 30%",
            "biaya": "Rendah"
        },
        {
            "judul": "Optimasi Layanan Fiber Optic",
            "deskripsi": "Pelanggan Fiber optic dengan layanan tambahan memiliki tingkat churn tertinggi. Evaluasi harga paket bundling dan kualitas layanan.",
            "dampak": "Potensi pengurangan churn: 20%",
            "biaya": "Tinggi"
        },
        {
            "judul": "Perbaikan Metode Pembayaran",
            "deskripsi": "Pelanggan dengan pembayaran Electronic check memiliki tingkat churn 15% lebih tinggi. Dorong konversi ke metode pembayaran otomatis.",
            "dampak": "Potensi pengurangan churn: 10%",
            "biaya": "Rendah"
        }
    ]

    for i, rec in enumerate(recommendations):
        with st.expander(f"{i+1}. {rec['judul']}"):
            st.markdown(f"**Deskripsi:** {rec['deskripsi']}")
            st.markdown(f"**Dampak Potensial:** {rec['dampak']}")
            st.markdown(f"**Estimasi Biaya Implementasi:** {rec['biaya']}")

    st.subheader("📈 Proyeksi ROI dari Program Retensi")
    st.markdown("Berdasarkan analisis biaya-manfaat, berikut proyeksi ROI dari implementasi program retensi:")

    fig3, ax3 = plt.subplots(figsize=(10, 6))
    months = ['Bulan 1', 'Bulan 3', 'Bulan 6', 'Bulan 12']
    roi_values = [-50, 20, 100, 250]  # Simulasi ROI dalam persentase

    ax3.plot(months, roi_values, marker='o', linewidth=3, markersize=10, color='#2196f3')
    ax3.fill_between(months, roi_values, alpha=0.2, color='#2196f3')
    ax3.axhline(y=0, color='r', linestyle='-', alpha=0.3)
    ax3.set_title('Proyeksi ROI Program Retensi Pelanggan', fontsize=14)
    ax3.set_ylabel('ROI (%)', fontsize=12)
    ax3.grid(True, alpha=0.3)

    # Tambahkan nilai pada titik data
    for i, v in enumerate(roi_values):
        ax3.text(i, v+10, f'{v}%', ha='center', fontweight='bold')

    st.pyplot(fig3)

# Footer
st.markdown("---")
st.markdown('''
<div style='text-align: center; color: #666;'>
    <p>Customer Churn Prediction System &copy; 2024 | Powered by Machine Learning</p>
    <p><small>Model Accuracy: 81.2% | F1-Score: 0.78 | Last Updated: December 2024</small></p>
</div>
''', unsafe_allow_html=True)
"""

# Simpan kode Streamlit ke file
with open('churn_prediction_app.py', 'w') as f:
    f.write(streamlit_code)

print("Kode aplikasi Streamlit telah disimpan sebagai 'churn_prediction_app.py'")
print("File requirements.txt juga perlu dibuat untuk deployment")

# Simpan requirements.txt
requirements = """
streamlit==1.30.0
pandas==2.1.3
numpy==1.26.2
scikit-learn==1.4.0
matplotlib==3.8.2
seaborn==0.13.0
joblib==1.3.2
missingno==0.5.2
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("File requirements.txt telah disimpan")
print("\n" + "="*60)
print("PERSIAPAN DEPLOYMENT SELESAI")
print("IKUTI LANGKAH-LANGKAH BERIKUT UNTUK DEPLOY KE STREAMLIT CLOUD:")
print("1. Simpan semua file di GitHub repository")
print("2. Buka Streamlit Cloud (share.streamlit.io)")
print("3. Deploy aplikasi dengan menghubungkan repository GitHub")
print("4. Setel main file ke 'churn_prediction_app.py'")
print("5. Tunggu proses deployment selesai dan aplikasi siap digunakan")
print("="*60)